<footer class="bank-footer">
	<div class="footer-container">

		<div class="footer-section">
      		<h3>INFINITY BANK</h3>
			<ul>
				<li>Your Trusted Financial Partner</li>
				<li>Head Office: Botad, India</li>
				<li>Email: padaniyash007@gmail.com</li>
				<li>Phone: +91 99241 80531</li>
			</ul>
    	</div>

		<div class="footer-section">
		<h3>Our Services</h3>
		<ul>
			<li>Savings Account</li>
			<li>Fixed Deposit</li>
			<li>Gold Loan</li>
			<li>Debit Card</li>
			<li>Mobile Banking</li>
		</ul>
    	</div>

		<div class="footer-section">
		<h3>Help & Support</h3>
		<ul>
			<li><a href="#">FAQs</a></li>
			<li><a href="#">Customer Care</a></li>
			<li><a href="#">Report Fraud</a></li>
			<li><a href="#">About Us</a></li>
			<li><a href="#">Privacy Policy</a></li>
			<li><a href="#">Terms & Conditions</a></li>
		</ul>
    	</div>

		<div class="footer-section">
			<h4>Follow Us</h4>
			<div class="socials">
				<a href="#"><i class="fa-brands fa-instagram" style="font-size:30px;"></i></a>
				<a href="#"><i class="fa-brands fa-linkedin" style="font-size:30px;"></i></a>
				<a href="#"><i class="fab fa-github" style="font-size:30px;"></i></a>
			</div>
		</div>

	</div>

	<div class="copy">
		© 2026 INFINITY BANK • All rights reserved
	</div>
</footer>